// Generated by CoffeeScript 1.4.0
(function() {

  Ext.define("StoreSample.model.Child", {
    extend: "Ext.data.Model",
    config: {
      fields: [
        {
          name: "name",
          type: "string"
        }, {
          name: "age",
          type: "int"
        }
      ]
    }
  });

}).call(this);
